[project]
name = "genrm-finetune"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "mlx-lm>=0.30.7",
    "pandas>=3.0.0",
    "transformers>=5.2.0",
]
